networks:
  db:
    attachable: true
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:14-alpine
    labels:
    - com.centurylinklabs.watchtower.enable=false
    - traefik.enable=false
    networks:
    - db
    restart: unless-stopped
    volumes:
    - /home/veerendra/volumes/postgres:/var/lib/postgresql/data:rw
