---
networks:
  public:
    attachable: true
    internal: false
  private:
    attachable: true
    internal: true

volumes:
  acme:

services:
  traefik:
    image: traefik:latest
    hostname: traefik
    container_name: traefik
    restart: unless-stopped
    environment:
      DUCKDNS_TOKEN: "${DUCKDNS_TOKEN}"
      CLOUDFLARE_DNS_API_TOKEN: "${CLOUDFLARE_DNS_API_TOKEN}"
    ports:
      - 80:80/tcp
      - 443:443/tcp
    networks:
      - public
      - private
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/letsencrypt
