---
networks:
  db:
    attachable: true

services:
  postgres:
    image: postgres:14-alpine
    hostname: postgres
    container_name: postgres
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=false
      - traefik.enable=false
    volumes:
      - /home/veerendra/volumes/postgres:/var/lib/postgresql/data:rw
    networks:
      - db
